# This list populates the "/" autocomplete menu in Telegram (capped under 100 to prevent errors).
BOT_COMMANDS = [
    BotCommand("start", "Welcome message"),
    BotCommand("help", "List all commands"),
    BotCommand("chat", "Toggle AI chat mode"),
    BotCommand("persona", "Set bot personality"),
    BotCommand("quiz", "Trivia round"),
    BotCommand("truth", "Truth question"),
    BotCommand("dare", "Dare challenge"),
    BotCommand("wyr", "Would you rather"),
    BotCommand("nhie", "Never have I ever"),
    BotCommand("rps", "Rock paper scissors"),
    BotCommand("riddle", "Get a riddle"),
    BotCommand("riddleanswer", "Answer active riddle"),
    BotCommand("scramble", "Unscramble a word"),
    BotCommand("unscramble", "Answer active scramble"),
    BotCommand("guess", "Guess a number 1-20"),
    BotCommand("leaderboard", "Game win rankings"),
    BotCommand("dice", "Roll a dice"),
    BotCommand("darts", "Throw darts"),
    BotCommand("basketball", "Shoot a basketball"),
    BotCommand("bowling", "Bowl a strike"),
    BotCommand("football", "Kick a football"),
    BotCommand("slot", "Spin slot machine"),
    BotCommand("oracle", "Ask the oracle"),
    BotCommand("tarot", "Draw a tarot card"),
    BotCommand("aura", "Read aura"),
    BotCommand("emojiaura", "Emoji energy reading"),
    BotCommand("fate", "Cryptic fate"),
    BotCommand("whisper", "Secretly DM someone"),
    BotCommand("lore", "Group lore drop"),
    BotCommand("starsign", "Zodiac reading"),
    BotCommand("confess", "Anonymous confession"),
    BotCommand("bestie", "Declare a bestie"),
    BotCommand("duo", "Generate a duo name"),
    BotCommand("friendship", "Compatibility score"),
    BotCommand("tagbestie", "Ping your bestie"),
    BotCommand("squad", "Active friend group"),
    BotCommand("loyalty", "Loyalty score"),
    BotCommand("ship", "Ship two people"),
    BotCommand("roast", "Playful roast"),
    BotCommand("compliment", "Nice compliment"),
    BotCommand("8ball", "Magic 8-ball"),
    BotCommand("vibe", "Vibe check chat"),
    BotCommand("quote", "Random quote"),
    BotCommand("crush", "Pick a crush"),
    BotCommand("clearcrush", "Clear your crush"),
    BotCommand("randomship", "Random ship pair"),
    BotCommand("secretadmirer", "Anonymous kind DM"),
    BotCommand("id", "Get user/chat ID"),
    BotCommand("info", "User info card"),
    BotCommand("remind", "Set a reminder"),
    BotCommand("mute", "Mute a user (admin)"),
    BotCommand("unmute", "Unmute a user (admin)"),
    BotCommand("ban", "Ban a user (admin)"),
    BotCommand("kick", "Kick a user (admin)"),
    BotCommand("warn", "Warn a user (admin)"),
    BotCommand("rules", "Show group rules"),
    BotCommand("warnings", "Check warnings"),
    BotCommand("clearwarns", "Clear warnings (admin)"),
    BotCommand("pin", "Pin message (admin)"),
    BotCommand("unpin", "Unpin message (admin)"),
    BotCommand("purge", "Delete messages (admin)"),
    BotCommand("setrules", "Set rules (admin)"),
    BotCommand("lock", "Lock chat (admin)"),
    BotCommand("unlock", "Unlock chat (admin)"),
    BotCommand("stats", "Group activity stats"),
    BotCommand("topactive", "Top active members"),
    BotCommand("msgcount", "Message count"),
    BotCommand("groupinfo", "Group info card"),
    BotCommand("afk", "Mark yourself away"),
    BotCommand("report", "Report to admins"),
    BotCommand("poll", "Create a poll"),
    BotCommand("rank", "Activity rank tier"),
    BotCommand("setwelcome", "Custom welcome"),
    BotCommand("setgoodbye", "Custom goodbye"),
    BotCommand("invite", "Fresh invite link"),
    BotCommand("joined", "Recent joins log"),
    BotCommand("left", "Recent leaves log"),
    BotCommand("hangman", "Start hangman"),
    BotCommand("hangmanguess", "Guess a letter"),
    BotCommand("tictactoe", "Challenge TTT"),
    BotCommand("ttt", "Make TTT move"),
    BotCommand("wordchain", "Start word chain"),
    BotCommand("chainword", "Submit chain word"),
    BotCommand("trivia", "Trivia by category"),
    BotCommand("wordle", "Get today's wordle"),
    BotCommand("wordleguess", "Guess wordle"),
    BotCommand("daily", "Claim daily coins"),
    BotCommand("balance", "Check coin balance"),
    BotCommand("rob", "Rob someone"),
    BotCommand("gamble", "Gamble coins"),
    BotCommand("richest", "Coin leaderboard"),
    BotCommand("moodboard", "Aesthetic mood"),
    BotCommand("dream", "Dream interpretation"),
    BotCommand("manifest", "Affirmation card"),
    BotCommand("matchmaker", "Pair random members"),
    BotCommand("friendshiptest", "Friendship quiz"),
    BotCommand("hug", "Hug someone"),
    BotCommand("pat", "Pat someone"),
    BotCommand("highfive", "High-five"),
    BotCommand("timecapsule", "Lock a message"),
    BotCommand("capsules", "List capsules"),
]
