"""Configuration for Midnight Oracle; additive Phase 2-5 settings live here."""
from __future__ import annotations
import os
from zoneinfo import ZoneInfo
BOT_TOKEN=os.getenv('BOT_TOKEN','').strip(); OPENAI_API_KEY=os.getenv('OPENAI_API_KEY','').strip(); OPENAI_MODEL=os.getenv('OPENAI_MODEL','gpt-4o').strip() or 'gpt-4o'; DATABASE_PATH=os.getenv('ORACLE_DATABASE_PATH','midnight_oracle.sqlite3'); TIMEZONE_NAME=os.getenv('ORACLE_TIMEZONE','Asia/Kolkata'); TIMEZONE=ZoneInfo(TIMEZONE_NAME); WEBAPP_URL=os.getenv('ORACLE_WEBAPP_URL','').strip()
ENGAGEMENT_THRESHOLD=6; AMBIENT_ENGAGEMENT_RATE=.30; PER_MEMBER_COOLDOWN_SECONDS=600; PER_GROUP_COOLDOWN_SECONDS=600; MAX_AMBIENT_REPLIES_PER_HOUR=2; SERIOUS_CONVERSATION_COOLDOWN_SECONDS=1200; SCHEDULED_MESSAGE_GAP_SECONDS=14400; MEMORY_INTEREST_LIMIT=10; MEMORY_THEME_LIMIT=5; MEMORY_WORRY_LIMIT=10; MEMORY_WIN_LIMIT=10; MEMORY_JOKE_LIMIT=10; MEMORY_RECENT_DAYS=30; GROUP_RECENT_MESSAGE_LIMIT=10; MOOD_WINDOW=10
MORNING_HOUR=7; MORNING_MINUTE=30; EVENING_HOUR=20; EVENING_MINUTE=0; LATE_NIGHT_START=23; LATE_NIGHT_END=3; THREE_AM_START=0; THREE_AM_END=3
JOKE_MAX_PER_GROUP=20; JOKE_CALLBACK_PROBABILITY=.15; JOKE_CALLBACK_GAP_SECONDS=172800; ABSENCE_DAYS=5; ABSENCE_PING_GAP_DAYS=14; ABSENCE_CHECK_HOUR=14; MAX_STICKER_EVENTS_PER_HOUR=3; SECRET_EVENT_MAX_WEEKLY=2; MAX_ACHIEVEMENTS_PER_EVENT=3; GAME_POLL_SECONDS=60
FALLBACK_REPLIES=(
    'Haan. Suna. ☾',
    'Yahin hoon. Bolo.',
    'Hmm… midnight sun raha hai.',
    'Batao. Kya chal raha hai?',
    'haan, bolo. 🌙',
    'I’m listening. No rush.',
    'Achha… ab asli baat batao.',
    'Haan. I’m here.',
)
